[phases.install]
cmds = ["rm -rf node_modules package-lock.json && npm cache clean --force && npm install --force --legacy-peer-deps --omit=optional"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve dist -s -l $PORT"
